version: '2'

services:

  spi:

    build: .

    devices:
      # the spi bus
      - "/dev/ttyAMA0:/dev/ttyAMA0"
    volumes:
      - "./:/srv"
    command: python /srv/spidev_test.py
    # command: spidev_test -D /dev/spidev0.0
    privileged: true

